In [38]:
import torch
import numpy as np

import data from numpy

In [39]:
data_np_1 = np.array([2,3])
data_np_2 = np.ones((2,3))
t1 = torch.from_numpy(data_np_1)
t2 = torch.from_numpy(data_np_2)
print("1 tensor = ",t1)
print("2 tensor = ",t2)
print(" 1 type ",t1.type())
print(" 2 type ",t2.type())

1 tensor =  tensor([2, 3])
2 tensor =  tensor([[1., 1., 1.],
        [1., 1., 1.]])
 1 type  torch.LongTensor
 2 type  torch.DoubleTensor


import data from list

In [40]:
t1 = torch.tensor([1,2,3,4,5])
t2 = torch.IntTensor([1,2,3,4,5])
print("T1 type = ",t1.type())
print("T1 type = ",t2.type())
t2

T1 type =  torch.LongTensor
T1 type =  torch.IntTensor


tensor([1, 2, 3, 4, 5], dtype=torch.int32)

Tensor 跟 tensor 的差別在於前者是直接接收一個維度的大小之後隨機自動產生對應大小的tensor   
tensor 則是可以直接輸入一個list將他轉換成tensor的資料型態         
FloatTensor 可以輸入一個維度自動轉換成隨機的floartensor,也可以直接輸入一個list轉換成tensor的型態     
IntTensor 的用法跟FloatTensor相同


In [41]:
T1 = torch.IntTensor([3])
T2 = torch.FloatTensor([3])
T3 = torch.Tensor(3)
print("T1 = ",T1," type()",T1.type())
print("T2 = ",T2," type()",T2.type())
print("T3 = ",T3," type()",T3.type())

T1 =  tensor([3], dtype=torch.int32)  type() torch.IntTensor
T2 =  tensor([3.], dtype=torch.float32)  type() torch.FloatTensor
T3 =  tensor([4.6721e-310, 4.6721e-310, 3.1620e-322])  type() torch.DoubleTensor


In [42]:
T1 = torch.IntTensor([1,2,3,4,5])
T2 = torch.FloatTensor([1.5,2.5,3.5,4.5,5.5])
T3 = torch.Tensor(3)
print("T1 = ",T1," type()",T1.type())
print("T2 = ",T2," type()",T2.type())
print("T3 = ",T3," type()",T3.type())

T1 =  tensor([1, 2, 3, 4, 5], dtype=torch.int32)  type() torch.IntTensor
T2 =  tensor([1.5000, 2.5000, 3.5000, 4.5000, 5.5000], dtype=torch.float32)  type() torch.FloatTensor
T3 =  tensor([6.9450e-310, 6.9450e-310, 1.5810e-322])  type() torch.DoubleTensor


In [43]:
T1 = torch.IntTensor(2,3)
T2 = torch.FloatTensor(2,3)
T3 = torch.Tensor(2,3)
print("T1 = ",T1," type()",T1.type())
print("T2 = ",T2," type()",T2.type())
print("T3 = ",T3," type()",T3.type())

T1 =  tensor([[-1535642384,       22017, -1535782192],
        [      22017,          80,           0]], dtype=torch.int32)  type() torch.IntTensor
T2 =  tensor([[-3.8914e-17,  3.0852e-41, -5.3767e-17],
        [ 3.0852e-41,  1.1210e-43,  0.0000e+00]], dtype=torch.float32)  type() torch.FloatTensor
T3 =  tensor([[4.6721e-310, 6.9450e-310, 3.1620e-322],
        [3.9525e-322,  0.0000e+00, 4.6721e-310]])  type() torch.DoubleTensor


生成隨機數據      
empty 起始一個空的陣列    
torch.Tensor() 起始一個隨機的陣列    
torch.randint() 起始一個隨機的int陣列     
torch.randn() 起始一個高斯分佈的真列    
torch.normal(mean,std) 起始一個可以自定義mean std的高斯陣列    
torch.full() 全部都是某個值的tensor




In [45]:
torch.empty(10)
t1 = torch.Tensor(2,3)
print("t1 type = ",t1.type())


t1 type =  torch.DoubleTensor


In [51]:
torch.randint(1,10,(2,2)) #[min,max,(shape) ]
torch.randn(3,3) #gaussian
torch.normal(mean=torch.full([10],0.),std=torch.arange(1,0,-0.1))

tensor([ 0.6714, -0.5517, -0.7058, -0.2162,  0.1177,  1.0851,  0.3473, -0.4340,
        -0.0924,  0.1452])

In [60]:
t1 = torch.full([2,3],3.)

建立指定大小的陣列     
torch.ones 全one的     
torch.zeros 全zero的     
torch.eye 對角矩陣
torch.ones_like 可以做出一個跟輸入大小相同的one矩陣     
torch.zeros_like 可以做出一個跟輸入大小相同的zero矩陣     

In [70]:
a = torch.zeros(5,5)
b = torch.ones_like(a)
b.shape


torch.Size([5, 5])

隨機打散     
torch.randperm() 隨機打散給定數量的index

In [82]:
index = torch.randperm(10)
print("index = ",index)
a = torch.IntTensor(10,3)
print(a)
print(a[index])
# a[index]

index =  tensor([3, 6, 1, 4, 9, 2, 7, 0, 5, 8])
tensor([[ 2133933456,       32728,  2133933456],
        [      32728,          64,           0],
        [          0,       32727,          48],
        [          0,         209,           0],
        [-1535641936,       22017, -1541156320],
        [      22017,           1,           0],
        [          0,           0,           0],
        [          0,           0,           0],
        [-1540250672,       22017, -1554052576],
        [      22017,  1990968240,       32727]], dtype=torch.int32)
tensor([[          0,         209,           0],
        [          0,           0,           0],
        [      32728,          64,           0],
        [-1535641936,       22017, -1541156320],
        [      22017,  1990968240,       32727],
        [          0,       32727,          48],
        [          0,           0,           0],
        [ 2133933456,       32728,  2133933456],
        [      22017,           1,           0],
 